name: Build Page
on:
  push:
    branches:
      - main
  release:
    types: [published]

permissions:
  contents: read
  actions: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Run Page Build
        run: |
          rm -rf ./*
          git clone -b pageBuilder https://github.com/eclipse-xfsc/landingpage.git page
          cd page
          yarn install
          yarn build
          cd ..
          mv -f -v ./page/build/* . 
          rm -rf ./page
          git config --global user.name 'Page build Bot' 
          git config --global user.email 'pagebuildbot@memeti.com'
          git add -A .
          git commit -a -m "Bot update from eclipse gitlab"
          git push
